### ISSUE TITLE
임계 영역에 대해서 설명 2022.06.01

### ISSUE THREAD

**Issue by DaeAkin** [boardStudy/BoardStudy#107]

**Comment by jeonghs2015** [comment]
(https://velog.io/@hsjung2015/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C%EC%9E%84%EA%B3%84%EC%98%81%EC%97%ADCritical-Section)

**Comment by lovi0714** [comment]
https://velog.io/@lovi0714/임계-영역-Critical-Section
