### ISSUE TITLE
[Post] String을 비교할 때 equlas()로 비교해야 하는 이유 - 2022.03.30

### ISSUE THREAD

**Issue by DaeAkin** [boardStudy/BoardStudy#11]

**Comment by lovi0714** [comment]
https://velog.io/@lovi0714/String%EC%9D%84-%EB%B9%84%EA%B5%90%ED%95%A0-%EB%95%8C-equals%EB%A1%9C-%EB%B9%84%EA%B5%90%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0 완료 😀

**Comment by dahoon1006** [comment]
https://dahoon1006.tistory.com/25
비밀번호 1234
👍

**Comment by jeonghs2015** [comment]
(https://velog.io/@hsjung2015/equals)
