### ISSUE TITLE
[Post] 프로세서와 스레드의 차이 2022.04.06

### ISSUE THREAD

**Issue by DaeAkin** [boardStudy/BoardStudy#12]

**Comment by lovi0714** [comment]
https://velog.io/@lovi0714/프로세스Process와-스레드Thread 완료!

**Comment by dahoon1006** [comment]
https://dahoon1006.tistory.com/26 👍

**Comment by jeonghs2015** [comment]
동현님 
1. 프로세서와 스레드의 차이
2. 프로세스와 스레드의 차이
뭐가 정확한건가요?

**Comment by DaeAkin** [comment]
2222222

**Comment by jeonghs2015** [comment]
https://velog.io/@hsjung2015/JAVA%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4%EC%99%80-%EC%8A%A4%EB%A0%88%EB%93%9C%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90
