### ISSUE TITLE
[Post] OSI계층 정리 2022.04.27

### ISSUE THREAD

**Issue by DaeAkin** [boardStudy/BoardStudy#13]

**Comment by jeonghs2015** [comment]
물 데 네 트 세 프 응

**Comment by lovi0714** [comment]
https://velog.io/@lovi0714/OSI-7-Layer 완료

**Comment by dahoon1006** [comment]
https://dahoon1006.tistory.com/30
앞에서 터지니 뒤에서 피가나더라.....👍

**Comment by jeonghs2015** [comment]
https://velog.io/@hsjung2015/NETWORKOSI계층-정리
