### ISSUE TITLE
[ERROR] 회원가입시 404페이지로 이동하는 현상

### ISSUE THREAD

**Issue by DaeAkin** [boardStudy/BoardStudy#16]

**Comment by dahoon1006** [comment]
## 문제
Post 방식으로 signUp.do를 요청할 때 user/user/signUp.do로 호출됨.

## 해결
signUp.html 에서
`form action` 경로 오류
`user/signUp.do` --> `/user/singUp.do`

-- > 올바른 directory로 변경 완료
