### ISSUE TITLE
[Post] Resolver란 무엇인가 2022.05.04

### ISSUE THREAD

**Issue by DaeAkin** [boardStudy/BoardStudy#22]

**Comment by jeonghs2015** [comment]
제가 Revolver는 아는데요..

**Comment by lovi0714** [comment]
https://velog.io/@lovi0714/Resolver
이게 맞나용

**Comment by DaeAkin** [comment]
@lovi0714 

ㅇㅇ 이정도면 댈듯

**Comment by jeonghs2015** [comment]
https://velog.io/@hsjung2015/Resolver%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80

**Comment by dahoon1006** [comment]
https://dahoon1006.tistory.com/31
👍
