### ISSUE TITLE
[Post] Equals()와 Hashcode()를 override 해야하는 이유 2022.04.13

### ISSUE THREAD

**Issue by DaeAkin** [boardStudy/BoardStudy#39]

**Comment by jeonghs2015** [comment]
https://velog.io/@hsjung2015/JAVAEquals%EC%99%80-Hashcode%EB%A5%BC-%EC%9E%AC%EC%A0%95%EC%9D%98override-%ED%95%B4%EC%95%BC%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

hashcode 재정의는 아직 이해가 안되서 미작성..

**Comment by dahoon1006** [comment]
https://dahoon1006.tistory.com/28 
비밀번호 : 1234
쉽지 않네요.. 👍

**Comment by lovi0714** [comment]
https://velog.io/@lovi0714/Equals와-Hashcode를-override-해야하는-이유
완료!
