### ISSUE TITLE
[POST] HTTP vs HTTPS  2022.04.20

### ISSUE THREAD

**Issue by DaeAkin** [boardStudy/BoardStudy#41]

**Comment by jeonghs2015** [comment]
https://velog.io/@hsjung2015/WEBHTTP%EC%99%80-HTTPS-%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90

**Comment by lovi0714** [comment]
https://velog.io/@lovi0714/HTTPS

**Comment by dahoon1006** [comment]
https://dahoon1006.tistory.com/29
👍
