### ISSUE TITLE
[FEATURE] 이메일 인증

### ISSUE THREAD

**Issue by dahoon1006** [boardStudy/BoardStudy#90]
## 📌 FEATURE
Feat : 사용자 이메일에 발송 된 인증번호를 회원가입 페이지에 입력했을 때 일치시키기.
---
### ✅ Description 
---
1. 회원가입 Form에서 이메일을 입력한 뒤 인증하기 클릭
2. 입력한 이메일에 메일이 발송된다.
3. 이메일 본문에는 인증링크가 도착하게됨
4. 링크 클릭 시 alert(인증이 되었다는 문구가 뜨고, 로그인이 가능해짐)
: 메일 인증을 하면 [user_auth] 컬럼 0(default 설정) > 1로 바뀌면서 로그인 허용
### ✅ 주의 사항
---
5.13 전까지 완료

**Comment by DaeAkin** [comment]
그럼 이메일 인증을 하지 않은 사용자가 로그인을 시도하려고 하면 어떻게 해야 할까요?

**Comment by dahoon1006** [comment]
회원가입 시에 이메일 인증 없이 가입은 되나(defalut 0으로)
이메일 인증 없이 로그인을 시도하려고 하면, 서버에서 이메일 인증상태(0 or 1)를 확인 후 
- 인증 : 로그인이 됨.
- 미인증 : alert출력(이메일 인증을 진행해주세요.)
진행하려고 합니다!
