### ISSUE TITLE
[Post] CheckedException VS UnCheckedException 2022.05.11

### ISSUE THREAD

**Issue by DaeAkin** [boardStudy/BoardStudy#95]

**Comment by lovi0714** [comment]
https://velog.io/@lovi0714/예외

**Comment by dahoon1006** [comment]
https://dahoon1006.tistory.com/32
👍

**Comment by jeonghs2015** [comment]
https://velog.io/@hsjung2015/JAVA-Checked-Exception-Unchecked-Exception
